name: Docs

on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Compile the crate
        run: cargo build --verbose

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Add redirect for index.html
        run: echo '<meta http-equiv="refresh" content="0;url=index.html">' > target/doc/index.html

      - name: Remove lock file
        run: rm target/doc/.lock

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
